datasource:
  default: "development"
  development:
    username: sa
    password: sa
    url: "jdbc:h2:./database"
  production:
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}

ebean:
  migration:
    run: true